### ISSUE TITLE
Tracker: Documentation update

### ISSUE THREAD

**Issue by SweeXordious** [web3j/web3j#1670]
This issue will track the needed updates for the [Web3J](http://docs.web3j.io/) documentation.

- [ ] https://github.com/web3j/web3j/issues/1669
- [ ] https://github.com/web3j/web3j/issues/1664 and https://github.com/web3j/web3j/issues/1662
- [ ] https://github.com/web3j/web3j/issues/1660 Document how to increase it

**Comment by GHkrishna** [comment]
Hello @SweeXordious, I would like to work on this issue. I can work on the third issue in the list and then can move to the second, upon completing the previous one.

Regarding the documentation, can you please guide me to documentation guidelines, other assets, etc. that can help with documentation.

Also, regarding the same timeout issue, will the documentation surround around the solution provided in #1660 or are there any further possibilities that needs to be researched before documenting. I believe the solution provided must be enough since it helped with all kinds of timeouts with read, write, etc. Please let me know if otherwise.
